import AppWrapper from '@/components/AppWrapper'
import { api } from '@/services/api'
import { withSSRAuth } from '@/utils/with-ssr-auth'
import { GetServerSidePropsContext } from 'next'
import Head from 'next/head'
import { ReactElement } from 'react'
import { Home as HomeTemplate } from './home'
import { IProperties, propertiesSchema } from '@/schemas/properties-schema'

export type HomeProps = {
  properties: IProperties
  totalCountOfProperties: number
}

export default function Home(props: HomeProps) {
  return (
    <>
      <Head>
        <title>Início | ERent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate {...props} />
    </>
  )
}

export const getServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const response = await api({
    method: 'GET',
    endpoint: '/properties',
    context: context
  })

  const properties = propertiesSchema.parse(response.properties.slice(0, 6))

  return {
    props: {
      properties,
      totalCountOfProperties: response.totalCount
    }
  }
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <AppWrapper>{page}</AppWrapper>
}
